### ISSUE TITLE
Tree preservation orders

### ISSUE THREAD

**Issue by colmjude** [digital-land/data-standards-backlog#11]
# Tree preservation orders

A [Tree Preservation Order](https://www.gov.uk/guidance/tree-preservation-orders-and-trees-in-conservation-areas) is an order made by a local planning authority in England to protect specific trees, groups of trees or woodlands in the interests of amenity

## What

We have drafted [a specification for tree preservation orders](https://digital-land.github.io/specification/specification/tree-preservation-order/). It allows data providers to create digital records of their tree preservation orders, whether they cover a zone (such as woodland) or individual trees.

Currently, we are testing it with a number of Local planning authorities to see if it works for them. We are testing whether they can publish data that complies with the standard and whether the data produced contains the right valuable information.

## Why

Tree preservation orders place restrictions on what can be done to the tree, for example, cutting it down might be prohibited. This has an impact on development. If there is a tree, on a site, with a tree preservation order the development that will be deemed acceptable is different to a site without a tree preservation order. Therefore, it is important for anyone wishing to develop a site to know if there is a tree preservation order and what it covers.

If there was a complete digital record of tree preservation orders, software could be built to more easily determine if a site or development is impacted.

## What we're looking for

We'd like to know more about:

* if the standard includes all the data you'd expect it to include? If not, tell us what you think is missing?
* what would you use the data for?
* is there existing tree preservation order data?
* can you publish data that matches the standard?
* anything else we need to know about tree preservation orders

**Comment by mattlucht** [comment]
We've had a question from one the Open Digital Planner LPA partners about dates relating to TPOs:

`TPOs have in effect two start dates. The date they are “made” and therefore come into force for a period of 6 months and the date they are “confirmed” which is the date they become permanent.  The dates we have at present are confirmed dates for confirmed TPOS and made dates for unconfirmed TPOS. If we are to make reference to ‘made date’ there will be a bit of work to go through historic files to find out the date the orders were originally made. It would useful to have some clarification here.`

It's be interesting to know if this also applies to other LPAs?

**Comment by colmjude** [comment]
Also, it would be useful to know more about what these dates mean, if they used to make certain decisions and if so, what those decisions are.

For example, does a TPO have to be 'confirmed' before it affects a potential planning application?

**Comment by mattlucht** [comment]
I had a conversation with some of the team from Great Yarmouth – they've advised that a TPO that was `made` would have the same implications from a planning perspective as a TPO that is `confirmed`.

At present in their data the `made` date is overwritten with a `confirmed` date when the TPO hits that status. They're going to add two date fields `made-date` and `confirmed-date`.

For older TPOs they won't have the data, but this shouldn't be a problem. It will however be useful for new TPOs where in the case of an appeal it'd be important to not lose the `made` period.

**Comment by mattlucht** [comment]
Based on the above, I propose we look at the dates in the specification and potentially include a `made-date` and a `confirmed-date`. In the case of there only being one date present, would it make sense that we use that as the `confirmed-date`?
