### ISSUE TITLE
Backlog of planning concerns

### ISSUE THREAD

**Issue by colmjude** [digital-land/data-standards-backlog#23]
# Backlog of planning concerns

We have published [our complete list of planning concerns](https://digital-land.github.io/data-standards/what-we-are-working-on/backlog). This is a list of things we've heard about or people have told us about.

We plan to work through this list, exploring each thing and seeing if creating and opening up data will solve some users' needs.

If you think we are missing something, please let us know. Tell us:

* what we are missing
* you know about the planning area
* where you think the data would be useful, and why

**Comment by mattlucht** [comment]
On a recent call with Historic England there was reference to a dataset around previously listed buildings (I think!)

**Comment by colmjude** [comment]
@mattlucht as in buildings that were on the list of [listed buildings](#10), and that have now been removed?

**Comment by mattlucht** [comment]
@colmjude yes, although there's every chance that I misunderstood! If that is the case, maybe it implies that Listed Building records are removed from the dataset

**Comment by LanePlanning** [comment]
Development Consent Order boundary is missing from the data set. Work need to switch from shapefile to multi polygon but should be part of the planning database as orders are made under Planning Act 2008 for nationally significant infrastructure projects and contain power to develop and to restrict activities as well as temporary possession, compulsory acquisition and management of rights of access etc. See https://infrastructure.planninginspectorate.gov.uk/ for made and draft orders.
Pauleen.Lane.kc@planninginspectorate.gov.uk

**Comment by mattlucht** [comment]
> Development Consent Order boundary is missing from the data set. Work need to switch from shapefile to multi polygon but should be part of the planning database as orders are made under Planning Act 2008 for nationally significant infrastructure projects and contain power to develop and to restrict activities as well as temporary possession, compulsory acquisition and management of rights of access etc. See https://infrastructure.planninginspectorate.gov.uk/ for made and draft orders. [Pauleen.Lane.kc@planninginspectorate.gov.uk](mailto:Pauleen.Lane.kc@planninginspectorate.gov.uk)

thanks @LanePlanning i'll get this added to the backlog now so that we can keep track of it. Maybe we can arrange a quick chat so that I can understand a bit more about this? (matt.lucht1@levellingup.gov.uk)
