### ISSUE TITLE
Article 4 directions

### ISSUE THREAD

**Issue by colmjude** [digital-land/data-standards-backlog#9]
# Article 4 directions

An Article 4 direction is made by the local planning authority to remove all or some of the permitted development rights on a site in order to protect it

## What

We have created [a standard for Article 4 directions](https://digital-land.github.io/specification/specification/article-4-direction/) - this standard is currently in the piloting stage. Piloting means we have developed a standard, a handful of Local planning authorities are publishing data to the standard and the [planning data platform is collecting it](https://www.planning.data.gov.uk/dataset/article-4-direction-area).

## Why

Anyone looking to develop a site needs to know if a site has had development rights removed. This should be easy for computers to determine. However, there isn't a complete digital record of all Article 4 directions.

## What we're looking for

We'd like to know:

* if the standard covers everything about Article 4 directions you'd expect it to, and if not, what you think is missing
* are you using the data, if so, what for?
* what you think would improve the data?
* what are the difficulties, if any, in creating and publishing this data
* anything else you think we should know

**Comment by colmjude** [comment]
Some local planning authorities publish their article 4 direction data, including:

* [Newcastle](https://datamillnorth.org/dataset/newcastle-article-4-directions)

**Comment by mattlucht** [comment]
In a conversation with some LPAs they mentioned that there a multiple dates related to an Article 4. Namely, when the order was `made` and when it was `confirmed`. This is discussed in the [issue for TPOs](https://github.com/digital-land/data-standards-backlog/issues/11#issuecomment-1640069500)
